object Module {
    const val SPLASH = ":feature-splash"
    const val LOGIN = ":feature-login"
    const val CHARITY = ":feature-charity"
    const val COIN_EXCHANGE = ":feature-coin"
    const val QR_CODE = ""
    const val SETTING = ""
    const val VISIT_MINE = ""
    const val DASHBOARD = ""
    const val WALLET_PIN = ""
    const val MINING_MISSION = ""
    const val QUIZ = ""
    const val TRANSACTIONS = ""
    const val COUPON = ""
    const val WALLET_SETTING = ""
    const val ADDITIONAL_INFO = ""
    const val ADMINE = ""
    const val AGREEMENT = ""
    const val PROFILE_SETTING = ""
    const val TRANSFER = ""
}